###UserProfile

#Create empty UserProfileObject
POST http://localhost:8082/api/users
Content-Type: application/json

{
  "userId" : 1
}

###Get UserProfile Object
GET http://localhost:8082/api/users/me
X-User-Id: 1

### PUT UserProfile 
PUT http://localhost:8082/api/users/me
X-User-Id: 42
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "phoneNumber": "+49123456789"
}

### GET addresses
GET http://localhost:8082/api/users/me/addresses
X-User-Id: 42

###Add address
POST http://localhost:8082/api/users/me/addresses
X-User-Id: 42
Content-Type: application/json

{
  "street" : "patrick.street.1",
  "city" : "Lage",
  "postalCode" : "123456",
  "country" : "germany",
  "isDefault" : true
}

###Delete a address
DELETE http://localhost:8082/api/users/me/addresses/52
X-User-Id: 1

###Set address to default
PATCH http://localhost:8082/api/users/me/addresses/2/default
X-User-Id: 1

###Get summary
GET http://localhost:8082/api/users/me/summary
X-User-Id: 1

###Set imageUrl
PUT http://localhost:8082/api/users/me/image
X-User-Id: 1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< C:/Users/dein-name/Pictures/test.jpg
--boundary--

### Auth-Service
###Register
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "email" : "jond5567sfdsalf@gmail.com",
  "password" : "password123"
}

###Login
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email" : "jonfas@gmail.com",
  "password" : "password123"
}

###Product Service
#Create new category
POST http://localhost:8083/api/category
Content-Type: application/json

{
  "name" : "marlon´s Freizeit Spielsachen",
  "description" : "Hier sind alle Spielsachen von Marvin gelistet"
}

###Create new Product
POST http://localhost:8083/api/product
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Test Laptop
--boundary
Content-Disposition: form-data; name="description"

Ein sehr gutes Laptop
--boundary
Content-Disposition: form-data; name="price"

999.99
--boundary
Content-Disposition: form-data; name="stock"

2
--boundary
Content-Disposition: form-data; name="categoryId"

1
--boundary
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< /path/to/your/image.jpg
--boundary--

